# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Plack-Middleware-GepokX-ModSSL/project>
	:perl_version_from _:main;
	:version_from _:main;
	:readme_from _:main;
	:requires
		"base 0",
		"Crypt::X509 0",
		"DateTime 0",
		"Gepok 0.20",
		"MIME::Base64 0",
		"Net::SSLeay 0",
		"Plack 0",
		"strict 0";
	:test_requires
		"Test::More 0.61",
		"Net::SSL".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Plack/Middleware/GepokX/ModSSL.pm".

